
import "./globals.css";
export const metadata = {
  title: "Resume-Jd-matcher",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full overflow-x-hidden font-serif  "
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
